---
name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-typecheck-test:
    name: Code Quality & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set up Node.js (for pyright)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pyright
        run: npm install -g pyright

      - name: Set up virtual environment & install dependencies
        run: make install

      - name: Check code quality
        run: make check

      - name: Run code tests
        run: make test
